// Mocks generated by Mockito 5.4.6 from annotations
// in front_shared/test/sync/strategies/push_strategy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:front_shared/src/core/network/network_info.dart' as _i8;
import 'package:front_shared/src/data/local/database/app_database.dart' as _i4;
import 'package:front_shared/src/data/local/database/daos/base_dao.dart'
    as _i11;
import 'package:front_shared/src/data/remote/dto/sync_dtos.dart' as _i2;
import 'package:front_shared/src/data/remote/sync_api_service.dart' as _i7;
import 'package:front_shared/src/sync/core/entity_registry.dart' as _i10;
import 'package:front_shared/src/sync/core/sync_queue.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncPullResponseDto_0 extends _i1.SmartFake
    implements _i2.SyncPullResponseDto {
  _FakeSyncPullResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncPushResponseDto_1 extends _i1.SmartFake
    implements _i2.SyncPushResponseDto {
  _FakeSyncPushResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTableInfo_2<TableDsl extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.TableInfo<TableDsl, D1> {
  _FakeTableInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_3 extends _i1.SmartFake implements _i4.AppDatabase {
  _FakeAppDatabase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_4 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_5 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_6 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_7 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_8 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T2> extends _i1.SmartFake implements _i6.Future<T2> {
  _FakeFuture_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_10<T2 extends _i3.Table, D2> extends _i1.SmartFake
    implements _i3.InsertStatement<T2, D2> {
  _FakeInsertStatement_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_11<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.UpdateStatement<T1, D1> {
  _FakeUpdateStatement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_12<T2 extends _i3.HasResultSet, D1>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T2, D1> {
  _FakeSimpleSelectStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_13<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_14<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_15<T2 extends _i3.Table, D2> extends _i1.SmartFake
    implements _i3.DeleteStatement<T2, D2> {
  _FakeDeleteStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_16<T1> extends _i1.SmartFake
    implements _i3.Selectable<T1> {
  _FakeSelectable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_17 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncApiService extends _i1.Mock implements _i7.SyncApiService {
  MockSyncApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.SyncPullResponseDto> pull({
    required List<String>? entityTypes,
    DateTime? lastSyncTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pull, [], {
              #entityTypes: entityTypes,
              #lastSyncTime: lastSyncTime,
            }),
            returnValue: _i6.Future<_i2.SyncPullResponseDto>.value(
              _FakeSyncPullResponseDto_0(
                this,
                Invocation.method(#pull, [], {
                  #entityTypes: entityTypes,
                  #lastSyncTime: lastSyncTime,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.SyncPullResponseDto>);

  @override
  _i6.Future<_i2.SyncPushResponseDto> push(_i2.SyncPushRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#push, [request]),
            returnValue: _i6.Future<_i2.SyncPushResponseDto>.value(
              _FakeSyncPushResponseDto_1(
                this,
                Invocation.method(#push, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.SyncPushResponseDto>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);
}

/// A class which mocks [SyncQueue].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueue extends _i1.Mock implements _i9.SyncQueue {
  MockSyncQueue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  void enqueue(_i9.QueuedSync? sync) => super.noSuchMethod(
    Invocation.method(#enqueue, [sync]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i9.QueuedSync> getDueRetries() =>
      (super.noSuchMethod(
            Invocation.method(#getDueRetries, []),
            returnValue: <_i9.QueuedSync>[],
          )
          as List<_i9.QueuedSync>);

  @override
  void remove(String? syncId) => super.noSuchMethod(
    Invocation.method(#remove, [syncId]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EntityRegistry].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntityRegistry extends _i1.Mock implements _i10.EntityRegistry {
  MockEntityRegistry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get registeredEntityTypes =>
      (super.noSuchMethod(
            Invocation.getter(#registeredEntityTypes),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void register<T extends _i3.Table, D>({
    required String? entityType,
    required _i11.BaseDao<T, D>? dao,
    required D Function(Map<String, dynamic>)? fromJson,
    required Map<String, dynamic> Function(D)? toJson,
    dynamic Function(D)? toDomain,
  }) => super.noSuchMethod(
    Invocation.method(#register, [], {
      #entityType: entityType,
      #dao: dao,
      #fromJson: fromJson,
      #toJson: toJson,
      #toDomain: toDomain,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i11.BaseDao<_i3.Table, dynamic>? getDao(String? entityType) =>
      (super.noSuchMethod(Invocation.method(#getDao, [entityType]))
          as _i11.BaseDao<_i3.Table, dynamic>?);

  @override
  _i11.BaseDao<T, D>? getTypedDao<T extends _i3.Table, D>(String? entityType) =>
      (super.noSuchMethod(Invocation.method(#getTypedDao, [entityType]))
          as _i11.BaseDao<T, D>?);

  @override
  D? deserialize<D>(String? entityType, Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#deserialize, [entityType, json]))
          as D?);

  @override
  Map<String, dynamic>? serialize(String? entityType, dynamic data) =>
      (super.noSuchMethod(Invocation.method(#serialize, [entityType, data]))
          as Map<String, dynamic>?);

  @override
  dynamic toDomain(String? entityType, dynamic data) =>
      super.noSuchMethod(Invocation.method(#toDomain, [entityType, data]));

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllDirtyEntities() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDirtyEntities, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  bool isRegistered(String? entityType) =>
      (super.noSuchMethod(
            Invocation.method(#isRegistered, [entityType]),
            returnValue: false,
          )
          as bool);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BaseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseDao<T extends _i3.Table, D> extends _i1.Mock
    implements _i11.BaseDao<T, D> {
  MockBaseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TableInfo<T, D> get table =>
      (super.noSuchMethod(
            Invocation.getter(#table),
            returnValue: _FakeTableInfo_2<T, D>(
              this,
              Invocation.getter(#table),
            ),
          )
          as _i3.TableInfo<T, D>);

  @override
  _i4.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_3(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i4.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_4(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i12.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_5(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_6(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_7(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i5.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_8(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i6.Future<D?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i6.Future<D?>.value(),
          )
          as _i6.Future<D?>);

  @override
  _i6.Future<List<D>> findAllActive() =>
      (super.noSuchMethod(
            Invocation.method(#findAllActive, []),
            returnValue: _i6.Future<List<D>>.value(<D>[]),
          )
          as _i6.Future<List<D>>);

  @override
  _i6.Future<List<D>> findAllDirty() =>
      (super.noSuchMethod(
            Invocation.method(#findAllDirty, []),
            returnValue: _i6.Future<List<D>>.value(<D>[]),
          )
          as _i6.Future<List<D>>);

  @override
  _i6.Future<void> markDirty(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markDirty, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearDirty(String? id, DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#clearDirty, [id, syncedAt]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> upsertFromServer(D? entity) =>
      (super.noSuchMethod(
            Invocation.method(#upsertFromServer, [entity]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<T1> createStream<T1 extends Object>(
    _i5.QueryStreamFetcher<T1>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T1>.empty(),
          )
          as _i6.Stream<T1>);

  @override
  T1 alias<T1, D1>(_i3.ResultSetImplementation<T1, D1>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i12.dummyValue<T1>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T1);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T1> doWhenOpened<T1>(
    _i6.FutureOr<T1> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T1 v) => _i6.Future<T1>.value(v),
                ) ??
                _FakeFuture_9<T1>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T1>);

  @override
  _i3.InsertStatement<T1, D1> into<T1 extends _i3.Table, D1>(
    _i3.TableInfo<T1, D1>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_10<T1, D1>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T1, D1>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_11<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T1, R> select<T1 extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T1, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_12<T1, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T1, R>);

  @override
  _i3.JoinedSelectStatement<T1, R> selectOnly<T1 extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T1, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_13<T1, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T1, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_14<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T1, D1> delete<T1 extends _i3.Table, D1>(
    _i3.TableInfo<T1, D1>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_15<T1, D1>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T1, D1>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_16<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_16<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T1> transaction<T1>(
    _i6.Future<T1> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T1 v) => _i6.Future<T1>.value(v),
                ) ??
                _FakeFuture_9<T1>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T1>);

  @override
  _i6.Future<T1> exclusively<T1>(_i6.Future<T1> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T1 v) => _i6.Future<T1>.value(v),
                ) ??
                _FakeFuture_9<T1>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T1>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T1> runWithInterceptor<T1>(
    _i6.Future<T1> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T1 v) => _i6.Future<T1>.value(v),
                ) ??
                _FakeFuture_9<T1>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T1>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_17(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_17(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
