// Mocks generated by Mockito 5.4.6 from annotations
// in front_shared/test/sync/auto_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:front_shared/src/core/network/network_info.dart' as _i5;
import 'package:front_shared/src/sync/core/sync_manager.dart' as _i3;
import 'package:front_shared/src/sync/core/sync_state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncState_0 extends _i1.SmartFake implements _i2.SyncState {
  _FakeSyncState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResult_1 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncManager extends _i1.Mock implements _i3.SyncManager {
  MockSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.SyncState> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i4.Stream<_i2.SyncState>.empty(),
          )
          as _i4.Stream<_i2.SyncState>);

  @override
  _i2.SyncState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _FakeSyncState_0(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i2.SyncState);

  @override
  int get queueLength =>
      (super.noSuchMethod(Invocation.getter(#queueLength), returnValue: 0)
          as int);

  @override
  _i4.Future<_i2.SyncResult> sync({
    String? athleteId,
    DateTime? since,
    List<String>? entityTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sync, [], {
              #athleteId: athleteId,
              #since: since,
              #entityTypes: entityTypes,
            }),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(
                this,
                Invocation.method(#sync, [], {
                  #athleteId: athleteId,
                  #since: since,
                  #entityTypes: entityTypes,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  void startRetryTimer() => super.noSuchMethod(
    Invocation.method(#startRetryTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopRetryTimer() => super.noSuchMethod(
    Invocation.method(#stopRetryTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);
}
