// Mocks generated by Mockito 5.4.6 from annotations
// in front_shared/test/sync/entity_registry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i1;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:front_shared/src/data/local/database/app_database.dart' as _i3;
import 'package:front_shared/src/data/local/database/daos/base_dao.dart' as _i6;
import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTableInfo_0<TableDsl extends _i1.Table, D1> extends _i2.SmartFake
    implements _i1.TableInfo<TableDsl, D1> {
  _FakeTableInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_1 extends _i2.SmartFake implements _i3.AppDatabase {
  _FakeAppDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_2 extends _i2.SmartFake
    implements _i1.DatabaseConnection {
  _FakeDatabaseConnection_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_3 extends _i2.SmartFake
    implements _i1.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_4 extends _i2.SmartFake implements _i1.QueryExecutor {
  _FakeQueryExecutor_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_5 extends _i2.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_6 extends _i2.SmartFake
    implements _i1.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_7<T2> extends _i2.SmartFake implements _i5.Future<T2> {
  _FakeFuture_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_8<T2 extends _i1.Table, D2> extends _i2.SmartFake
    implements _i1.InsertStatement<T2, D2> {
  _FakeInsertStatement_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_9<T1 extends _i1.Table, D1> extends _i2.SmartFake
    implements _i1.UpdateStatement<T1, D1> {
  _FakeUpdateStatement_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_10<T2 extends _i1.HasResultSet, D1>
    extends _i2.SmartFake
    implements _i1.SimpleSelectStatement<T2, D1> {
  _FakeSimpleSelectStatement_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_11<FirstT extends _i1.HasResultSet, FirstD>
    extends _i2.SmartFake
    implements _i1.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_12<Row> extends _i2.SmartFake
    implements _i1.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_13<T2 extends _i1.Table, D2> extends _i2.SmartFake
    implements _i1.DeleteStatement<T2, D2> {
  _FakeDeleteStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_14<T1> extends _i2.SmartFake
    implements _i1.Selectable<T1> {
  _FakeSelectable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_15 extends _i2.SmartFake
    implements _i1.GenerationContext {
  _FakeGenerationContext_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseDao<T extends _i1.Table, D> extends _i2.Mock
    implements _i6.BaseDao<T, D> {
  MockBaseDao() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.TableInfo<T, D> get table =>
      (super.noSuchMethod(
            Invocation.getter(#table),
            returnValue: _FakeTableInfo_0<T, D>(
              this,
              Invocation.getter(#table),
            ),
          )
          as _i1.TableInfo<T, D>);

  @override
  _i3.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_1(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i3.AppDatabase);

  @override
  _i1.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_2(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i1.DatabaseConnection);

  @override
  _i1.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i7.dummyValue<_i1.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i1.SqlTypes);

  @override
  _i1.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_3(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i1.DriftDatabaseOptions);

  @override
  _i1.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_4(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i1.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_5(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i1.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_6(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i1.DatabaseConnectionUser);

  @override
  _i5.Future<D?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i5.Future<D?>.value(),
          )
          as _i5.Future<D?>);

  @override
  _i5.Future<List<D>> findAllActive() =>
      (super.noSuchMethod(
            Invocation.method(#findAllActive, []),
            returnValue: _i5.Future<List<D>>.value(<D>[]),
          )
          as _i5.Future<List<D>>);

  @override
  _i5.Future<List<D>> findAllDirty() =>
      (super.noSuchMethod(
            Invocation.method(#findAllDirty, []),
            returnValue: _i5.Future<List<D>>.value(<D>[]),
          )
          as _i5.Future<List<D>>);

  @override
  _i5.Future<void> markDirty(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markDirty, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearDirty(String? id, DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#clearDirty, [id, syncedAt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertFromServer(D? entity) =>
      (super.noSuchMethod(
            Invocation.method(#upsertFromServer, [entity]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<T1> createStream<T1 extends Object>(
    _i4.QueryStreamFetcher<T1>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T1>.empty(),
          )
          as _i5.Stream<T1>);

  @override
  T1 alias<T1, D1>(_i1.ResultSetImplementation<T1, D1>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i7.dummyValue<T1>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T1);

  @override
  void markTablesUpdated(Iterable<_i1.TableInfo<_i1.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i1.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i1.TableUpdate>> tableUpdates([
    _i1.TableUpdateQuery? query = const _i1.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i1.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i1.TableUpdate>>);

  @override
  _i5.Future<T1> doWhenOpened<T1>(
    _i5.FutureOr<T1> Function(_i1.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T1 v) => _i5.Future<T1>.value(v),
                ) ??
                _FakeFuture_7<T1>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T1>);

  @override
  _i1.InsertStatement<T1, D1> into<T1 extends _i1.Table, D1>(
    _i1.TableInfo<T1, D1>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_8<T1, D1>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i1.InsertStatement<T1, D1>);

  @override
  _i1.UpdateStatement<Tbl, R> update<Tbl extends _i1.Table, R>(
    _i1.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_9<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i1.UpdateStatement<Tbl, R>);

  @override
  _i1.SimpleSelectStatement<T1, R> select<T1 extends _i1.HasResultSet, R>(
    _i1.ResultSetImplementation<T1, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_10<T1, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i1.SimpleSelectStatement<T1, R>);

  @override
  _i1.JoinedSelectStatement<T1, R> selectOnly<T1 extends _i1.HasResultSet, R>(
    _i1.ResultSetImplementation<T1, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_11<T1, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i1.JoinedSelectStatement<T1, R>);

  @override
  _i1.BaseSelectStatement<_i1.TypedResult> selectExpressions(
    Iterable<_i1.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_12<_i1.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i1.BaseSelectStatement<_i1.TypedResult>);

  @override
  _i1.DeleteStatement<T1, D1> delete<T1 extends _i1.Table, D1>(
    _i1.TableInfo<T1, D1>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_13<T1, D1>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i1.DeleteStatement<T1, D1>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i1.Variable<Object>>? variables = const [],
    Set<_i1.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i1.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i1.Variable<Object>>? variables = const [],
    Set<_i1.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i1.QueryRow>> customWriteReturning(
    String? query, {
    List<_i1.Variable<Object>>? variables = const [],
    Set<_i1.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i1.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i1.QueryRow>>.value(<_i1.QueryRow>[]),
          )
          as _i5.Future<List<_i1.QueryRow>>);

  @override
  _i1.Selectable<_i1.QueryRow> customSelect(
    String? query, {
    List<_i1.Variable<Object>>? variables = const [],
    Set<_i1.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_14<_i1.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i1.Selectable<_i1.QueryRow>);

  @override
  _i1.Selectable<_i1.QueryRow> customSelectQuery(
    String? query, {
    List<_i1.Variable<Object>>? variables = const [],
    Set<_i1.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_14<_i1.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i1.Selectable<_i1.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T1> transaction<T1>(
    _i5.Future<T1> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T1 v) => _i5.Future<T1>.value(v),
                ) ??
                _FakeFuture_7<T1>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T1>);

  @override
  _i5.Future<T1> exclusively<T1>(_i5.Future<T1> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T1 v) => _i5.Future<T1>.value(v),
                ) ??
                _FakeFuture_7<T1>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T1>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i1.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T1> runWithInterceptor<T1>(
    _i5.Future<T1> Function()? action, {
    required _i1.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T1>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T1 v) => _i5.Future<T1>.value(v),
                ) ??
                _FakeFuture_7<T1>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T1>);

  @override
  _i1.GenerationContext $write(
    _i1.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_15(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i1.GenerationContext);

  @override
  _i1.GenerationContext $writeInsertable(
    _i1.TableInfo<_i1.Table, dynamic>? table,
    _i1.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_15(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i1.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
