// Mocks generated by Mockito 5.4.6 from annotations
// in front_shared/test/sync/sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:front_shared/src/core/network/network_info.dart' as _i7;
import 'package:front_shared/src/data/local/secure_storage/secure_storage_service.dart'
    as _i8;
import 'package:front_shared/src/sync/core/sync_queue.dart' as _i6;
import 'package:front_shared/src/sync/core/sync_state.dart' as _i2;
import 'package:front_shared/src/sync/strategies/pull_strategy.dart' as _i3;
import 'package:front_shared/src/sync/strategies/push_strategy.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PullStrategy].
///
/// See the documentation for Mockito's code generation for more information.
class MockPullStrategy extends _i1.Mock implements _i3.PullStrategy {
  MockPullStrategy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> execute({
    required String? athleteId,
    DateTime? since,
    List<String>? entityTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #athleteId: athleteId,
              #since: since,
              #entityTypes: entityTypes,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<DateTime?> getLastSyncTimestamp(String? athleteId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTimestamp, [athleteId]),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);
}

/// A class which mocks [PushStrategy].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushStrategy extends _i1.Mock implements _i5.PushStrategy {
  MockPushStrategy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SyncResult> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_0(this, Invocation.method(#execute, [])),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<int> retryQueuedSyncs() =>
      (super.noSuchMethod(
            Invocation.method(#retryQueuedSyncs, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [SyncQueue].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueue extends _i1.Mock implements _i6.SyncQueue {
  MockSyncQueue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  void enqueue(_i6.QueuedSync? sync) => super.noSuchMethod(
    Invocation.method(#enqueue, [sync]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i6.QueuedSync> getDueRetries() =>
      (super.noSuchMethod(
            Invocation.method(#getDueRetries, []),
            returnValue: <_i6.QueuedSync>[],
          )
          as List<_i6.QueuedSync>);

  @override
  void remove(String? syncId) => super.noSuchMethod(
    Invocation.method(#remove, [syncId]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i8.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> savePasswordHash(String? hash) =>
      (super.noSuchMethod(
            Invocation.method(#savePasswordHash, [hash]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPasswordHash() =>
      (super.noSuchMethod(
            Invocation.method(#getPasswordHash, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveUserRole(String? role) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserRole, [role]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserRole() =>
      (super.noSuchMethod(
            Invocation.method(#getUserRole, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
